POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl":"https://www.amazon.com.tr/dp/0132373815/ref=asc_df_01323738151602720600000?smid=A1UNQM1SR2CHM&linkCode=asn&creative=380341&creativeASIN=0132373815&tag=kitabinabaktr-21"
}